# Generated by Django 3.0.5 on 2021-01-25 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='time',
            new_name='pubdate',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='headline',
            new_name='title',
        ),
        migrations.AddField(
            model_name='news',
            name='language',
            field=models.CharField(default='en', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='url',
            field=models.URLField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
